# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTextEdit,
    QWidget)

class Ui_InstallForm(object):
    def setupUi(self, InstallForm):
        if not InstallForm.objectName():
            InstallForm.setObjectName(u"InstallForm")
        InstallForm.resize(960, 408)
        InstallForm.setMinimumSize(QSize(960, 400))
        InstallForm.setMaximumSize(QSize(960, 460))
        self.actionAbout = QAction(InstallForm)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(InstallForm)
        self.centralwidget.setObjectName(u"centralwidget")
        self.jservLines = QTextEdit(self.centralwidget)
        self.jservLines.setObjectName(u"jservLines")
        self.jservLines.setGeometry(QRect(30, 260, 601, 61))
        self.jservLines.setMaximumSize(QSize(8000, 400))
        self.lbJservs = QLabel(self.centralwidget)
        self.lbJservs.setObjectName(u"lbJservs")
        self.lbJservs.setGeometry(QRect(210, 236, 461, 21))
        self.lbJservs.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.txtVolpath = QLineEdit(self.centralwidget)
        self.txtVolpath.setObjectName(u"txtVolpath")
        self.txtVolpath.setGeometry(QRect(110, 206, 521, 27))
        self.bVolpath = QPushButton(self.centralwidget)
        self.bVolpath.setObjectName(u"bVolpath")
        self.bVolpath.setGeometry(QRect(649, 206, 111, 27))
        font = QFont()
        font.setPointSize(12)
        self.bVolpath.setFont(font)
        icon = QIcon(QIcon.fromTheme(u"computer"))
        self.bVolpath.setIcon(icon)
        self.bVolpath.setIconSize(QSize(24, 24))
        self.lbVolume = QLabel(self.centralwidget)
        self.lbVolume.setObjectName(u"lbVolume")
        self.lbVolume.setGeometry(QRect(40, 206, 69, 19))
        self.lbSynode = QLabel(self.centralwidget)
        self.lbSynode.setObjectName(u"lbSynode")
        self.lbSynode.setGeometry(QRect(48, 143, 61, 20))
        self.txtSynode = QLineEdit(self.centralwidget)
        self.txtSynode.setObjectName(u"txtSynode")
        self.txtSynode.setGeometry(QRect(109, 140, 131, 27))
        self.txtSynode.setMaxLength(12)
        self.txtIP = QLineEdit(self.centralwidget)
        self.txtIP.setObjectName(u"txtIP")
        self.txtIP.setGeometry(QRect(330, 140, 141, 27))
        self.txtIP.setMaxLength(39)
        self.lbIP = QLabel(self.centralwidget)
        self.lbIP.setObjectName(u"lbIP")
        self.lbIP.setGeometry(QRect(270, 143, 69, 19))
        self.lbPort = QLabel(self.centralwidget)
        self.lbPort.setObjectName(u"lbPort")
        self.lbPort.setGeometry(QRect(489, 143, 41, 20))
        self.txtPort = QLineEdit(self.centralwidget)
        self.txtPort.setObjectName(u"txtPort")
        self.txtPort.setGeometry(QRect(650, 140, 111, 27))
        self.txtPort.setMaxLength(6)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 951, 131))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.lbDomain = QLabel(self.groupBox)
        self.lbDomain.setObjectName(u"lbDomain")
        self.lbDomain.setGeometry(QRect(40, 100, 69, 19))
        self.txtDomain = QLineEdit(self.groupBox)
        self.txtDomain.setObjectName(u"txtDomain")
        self.txtDomain.setEnabled(False)
        self.txtDomain.setGeometry(QRect(110, 100, 211, 27))
        self.txtDomain.setMaxLength(12)
        self.lbRetry = QLabel(self.groupBox)
        self.lbRetry.setObjectName(u"lbRetry")
        self.lbRetry.setGeometry(QRect(450, 100, 61, 20))
        self.txtPswd2 = QLineEdit(self.groupBox)
        self.txtPswd2.setObjectName(u"txtPswd2")
        self.txtPswd2.setGeometry(QRect(530, 100, 231, 27))
        self.txtPswd2.setMaxLength(32)
        self.txtPswd2.setEchoMode(QLineEdit.EchoMode.Password)
        self.lbUserId = QLabel(self.groupBox)
        self.lbUserId.setObjectName(u"lbUserId")
        self.lbUserId.setGeometry(QRect(30, 73, 71, 20))
        self.txtPswd = QLineEdit(self.groupBox)
        self.txtPswd.setObjectName(u"txtPswd")
        self.txtPswd.setGeometry(QRect(530, 70, 231, 27))
        self.txtPswd.setMaxLength(32)
        self.txtPswd.setEchoMode(QLineEdit.EchoMode.Password)
        self.txtUserId = QLineEdit(self.groupBox)
        self.txtUserId.setObjectName(u"txtUserId")
        self.txtUserId.setGeometry(QRect(110, 70, 211, 27))
        self.txtUserId.setMaxLength(12)
        self.lbPswd = QLabel(self.groupBox)
        self.lbPswd.setObjectName(u"lbPswd")
        self.lbPswd.setGeometry(QRect(440, 72, 70, 19))
        self.bLogin = QPushButton(self.groupBox)
        self.bLogin.setObjectName(u"bLogin")
        self.bLogin.setEnabled(False)
        self.bLogin.setGeometry(QRect(775, 100, 161, 28))
        self.bRoot = QPushButton(self.groupBox)
        self.bRoot.setObjectName(u"bRoot")
        self.bRoot.setGeometry(QRect(775, 30, 161, 26))
        self.bRoot.setFont(font)
        self.bRoot.setIcon(icon)
        self.bRoot.setIconSize(QSize(24, 22))
        self.lbRoot = QLabel(self.groupBox)
        self.lbRoot.setObjectName(u"lbRoot")
        self.lbRoot.setGeometry(QRect(38, 30, 71, 20))
        self.txtResroot = QLineEdit(self.groupBox)
        self.txtResroot.setObjectName(u"txtResroot")
        self.txtResroot.setGeometry(QRect(110, 30, 651, 27))
        self.bSingup = QPushButton(self.groupBox)
        self.bSingup.setObjectName(u"bSingup")
        self.bSingup.setEnabled(False)
        self.bSingup.setGeometry(QRect(775, 70, 161, 28))
        self.lbHelplink = QLabel(self.groupBox)
        self.lbHelplink.setObjectName(u"lbHelplink")
        self.lbHelplink.setGeometry(QRect(870, 0, 61, 20))
        self.lbHelplink.setOpenExternalLinks(True)
        self.lbQr = QLabel(self.centralwidget)
        self.lbQr.setObjectName(u"lbQr")
        self.lbQr.setGeometry(QRect(780, 141, 170, 170))
        self.lbQr.setMaximumSize(QSize(200, 200))
        self.lbQr.setAutoFillBackground(False)
        self.bValidate = QPushButton(self.centralwidget)
        self.bValidate.setObjectName(u"bValidate")
        self.bValidate.setGeometry(QRect(540, 327, 91, 30))
        self.bWinserv = QPushButton(self.centralwidget)
        self.bWinserv.setObjectName(u"bWinserv")
        self.bWinserv.setEnabled(False)
        self.bWinserv.setGeometry(QRect(650, 327, 301, 30))
        self.bSetup = QPushButton(self.centralwidget)
        self.bSetup.setObjectName(u"bSetup")
        self.bSetup.setEnabled(True)
        self.bSetup.setGeometry(QRect(440, 327, 91, 30))
        self.lbIneach = QLabel(self.centralwidget)
        self.lbIneach.setObjectName(u"lbIneach")
        self.lbIneach.setGeometry(QRect(30, 236, 111, 19))
        self.txtSyncIns = QLineEdit(self.centralwidget)
        self.txtSyncIns.setObjectName(u"txtSyncIns")
        self.txtSyncIns.setGeometry(QRect(140, 236, 51, 21))
        self.txtSyncIns.setMaxLength(6)
        self.txtSyncIns.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.bPing = QPushButton(self.centralwidget)
        self.bPing.setObjectName(u"bPing")
        self.bPing.setEnabled(True)
        self.bPing.setGeometry(QRect(650, 290, 111, 27))
        self.txtWebport = QLineEdit(self.centralwidget)
        self.txtWebport.setObjectName(u"txtWebport")
        self.txtWebport.setGeometry(QRect(529, 140, 101, 27))
        self.txtWebport.setMaxLength(6)
        self.lbPort_2 = QLabel(self.centralwidget)
        self.lbPort_2.setObjectName(u"lbPort_2")
        self.lbPort_2.setGeometry(QRect(638, 143, 12, 20))
        self.chkReverseProxy = QCheckBox(self.centralwidget)
        self.chkReverseProxy.setObjectName(u"chkReverseProxy")
        self.chkReverseProxy.setGeometry(QRect(109, 173, 171, 21))
        self.lbPublicIP = QLabel(self.centralwidget)
        self.lbPublicIP.setObjectName(u"lbPublicIP")
        self.lbPublicIP.setGeometry(QRect(264, 174, 61, 20))
        self.txtPort_proxy = QLineEdit(self.centralwidget)
        self.txtPort_proxy.setObjectName(u"txtPort_proxy")
        self.txtPort_proxy.setGeometry(QRect(650, 170, 111, 27))
        self.txtPort_proxy.setMaxLength(6)
        self.txtWebport_proxy = QLineEdit(self.centralwidget)
        self.txtWebport_proxy.setObjectName(u"txtWebport_proxy")
        self.txtWebport_proxy.setGeometry(QRect(529, 170, 101, 27))
        self.txtWebport_proxy.setMaxLength(6)
        self.txtIP_proxy = QLineEdit(self.centralwidget)
        self.txtIP_proxy.setObjectName(u"txtIP_proxy")
        self.txtIP_proxy.setGeometry(QRect(330, 170, 141, 27))
        self.txtIP_proxy.setMaxLength(39)
        self.lbPort_3 = QLabel(self.centralwidget)
        self.lbPort_3.setObjectName(u"lbPort_3")
        self.lbPort_3.setGeometry(QRect(638, 172, 12, 20))
        self.lbPort_4 = QLabel(self.centralwidget)
        self.lbPort_4.setObjectName(u"lbPort_4")
        self.lbPort_4.setGeometry(QRect(489, 174, 41, 20))
        self.txtimeout = QLineEdit(self.centralwidget)
        self.txtimeout.setObjectName(u"txtimeout")
        self.txtimeout.setGeometry(QRect(730, 260, 31, 20))
        font1 = QFont()
        font1.setFamilies([u"Serif"])
        font1.setPointSize(10)
        self.txtimeout.setFont(font1)
        self.txtimeout.setMaxLength(4)
        self.txtimeout.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.txtimeout.setReadOnly(False)
        self.lbTimeout = QLabel(self.centralwidget)
        self.lbTimeout.setObjectName(u"lbTimeout")
        self.lbTimeout.setGeometry(QRect(650, 260, 81, 16))
        self.lblink = QLabel(self.centralwidget)
        self.lblink.setObjectName(u"lblink")
        self.lblink.setGeometry(QRect(30, 340, 361, 20))
        self.lblink.setOpenExternalLinks(True)
        InstallForm.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(InstallForm)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 960, 23))
        self.menuPortfolio_0_7 = QMenu(self.menubar)
        self.menuPortfolio_0_7.setObjectName(u"menuPortfolio_0_7")
        InstallForm.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(InstallForm)
        self.statusbar.setObjectName(u"statusbar")
        InstallForm.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtResroot, self.bRoot)
        QWidget.setTabOrder(self.bRoot, self.txtUserId)
        QWidget.setTabOrder(self.txtUserId, self.txtDomain)
        QWidget.setTabOrder(self.txtDomain, self.txtPswd)
        QWidget.setTabOrder(self.txtPswd, self.txtPswd2)
        QWidget.setTabOrder(self.txtPswd2, self.bSingup)
        QWidget.setTabOrder(self.bSingup, self.bLogin)
        QWidget.setTabOrder(self.bLogin, self.txtSynode)
        QWidget.setTabOrder(self.txtSynode, self.txtIP)
        QWidget.setTabOrder(self.txtIP, self.txtWebport)
        QWidget.setTabOrder(self.txtWebport, self.txtPort)
        QWidget.setTabOrder(self.txtPort, self.chkReverseProxy)
        QWidget.setTabOrder(self.chkReverseProxy, self.txtIP_proxy)
        QWidget.setTabOrder(self.txtIP_proxy, self.txtWebport_proxy)
        QWidget.setTabOrder(self.txtWebport_proxy, self.txtPort_proxy)
        QWidget.setTabOrder(self.txtPort_proxy, self.txtVolpath)
        QWidget.setTabOrder(self.txtVolpath, self.bVolpath)
        QWidget.setTabOrder(self.bVolpath, self.txtSyncIns)
        QWidget.setTabOrder(self.txtSyncIns, self.jservLines)
        QWidget.setTabOrder(self.jservLines, self.bPing)
        QWidget.setTabOrder(self.bPing, self.txtimeout)
        QWidget.setTabOrder(self.txtimeout, self.bSetup)
        QWidget.setTabOrder(self.bSetup, self.bValidate)
        QWidget.setTabOrder(self.bValidate, self.bWinserv)

        self.menubar.addAction(self.menuPortfolio_0_7.menuAction())
        self.menuPortfolio_0_7.addAction(self.actionAbout)

        self.retranslateUi(InstallForm)

        QMetaObject.connectSlotsByName(InstallForm)
    # setupUi

    def retranslateUi(self, InstallForm):
        InstallForm.setWindowTitle(QCoreApplication.translate("InstallForm", u"Portfolio Synode 0.7", None))
        self.actionAbout.setText(QCoreApplication.translate("InstallForm", u"About", None))
        self.lbJservs.setText(QCoreApplication.translate("InstallForm", u"seconds with peers, e. g. X:   http://127.0.0.1:8964/jserv-album", None))
#if QT_CONFIG(whatsthis)
        self.txtVolpath.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtVolpath.setText(QCoreApplication.translate("InstallForm", u"../vol", None))
        self.txtVolpath.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Volume is where the data saved at local node.", None))
        self.bVolpath.setText(QCoreApplication.translate("InstallForm", u"&...", None))
#if QT_CONFIG(shortcut)
        self.bVolpath.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.lbVolume.setText(QCoreApplication.translate("InstallForm", u"Volume:", None))
        self.lbSynode.setText(QCoreApplication.translate("InstallForm", u"Synode", None))
#if QT_CONFIG(whatsthis)
        self.txtSynode.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtSynode.setText("")
        self.txtSynode.setPlaceholderText(QCoreApplication.translate("InstallForm", u"12 Bit GUID, must not null", None))
#if QT_CONFIG(whatsthis)
        self.txtIP.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtIP.setText("")
        self.txtIP.setPlaceholderText(QCoreApplication.translate("InstallForm", u"0.0.0.0", None))
        self.lbIP.setText(QCoreApplication.translate("InstallForm", u"Local IP", None))
        self.lbPort.setText(QCoreApplication.translate("InstallForm", u"Port", None))
#if QT_CONFIG(whatsthis)
        self.txtPort.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPort.setText("")
        self.txtPort.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8964", None))
        self.groupBox.setTitle(QCoreApplication.translate("InstallForm", u"  Synchronization Domain Identity - Market URA", None))
        self.lbDomain.setText(QCoreApplication.translate("InstallForm", u"Domain:", None))
#if QT_CONFIG(whatsthis)
        self.txtDomain.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtDomain.setText(QCoreApplication.translate("InstallForm", u"zsu", None))
        self.txtDomain.setPlaceholderText(QCoreApplication.translate("InstallForm", u"12 Bit Market wide ID, must not null", None))
        self.lbRetry.setText(QCoreApplication.translate("InstallForm", u"Confirm:", None))
#if QT_CONFIG(whatsthis)
        self.txtPswd2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPswd2.setText("")
        self.txtPswd2.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Confirm Password", None))
        self.lbUserId.setText(QCoreApplication.translate("InstallForm", u"<html><head/><body><p align=\"right\">User ID:</p></body></html>", None))
#if QT_CONFIG(whatsthis)
        self.txtPswd.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPswd.setText("")
        self.txtPswd.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Max 32 Chars", None))
#if QT_CONFIG(whatsthis)
        self.txtUserId.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtUserId.setText("")
        self.txtUserId.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Registered admin ID", None))
        self.lbPswd.setText(QCoreApplication.translate("InstallForm", u"Password:", None))
        self.bLogin.setText(QCoreApplication.translate("InstallForm", u"&Login", None))
#if QT_CONFIG(shortcut)
        self.bLogin.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.bRoot.setText(QCoreApplication.translate("InstallForm", u"&...", None))
#if QT_CONFIG(shortcut)
        self.bRoot.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.lbRoot.setText(QCoreApplication.translate("InstallForm", u"Res Root:", None))
#if QT_CONFIG(whatsthis)
        self.txtResroot.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtResroot.setText(QCoreApplication.translate("InstallForm", u"./registry", None))
        self.txtResroot.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Path to the registered resources.", None))
        self.bSingup.setText(QCoreApplication.translate("InstallForm", u"&Sing up", None))
#if QT_CONFIG(shortcut)
        self.bSingup.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.lbHelplink.setText(QCoreApplication.translate("InstallForm", u"Help", None))
        self.lbQr.setText("")
        self.bValidate.setText(QCoreApplication.translate("InstallForm", u"&Test Run", None))
#if QT_CONFIG(shortcut)
        self.bValidate.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.bWinserv.setText(QCoreApplication.translate("InstallForm", u"Install as &Windows Service", None))
#if QT_CONFIG(shortcut)
        self.bWinserv.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.bSetup.setText(QCoreApplication.translate("InstallForm", u"&Save", None))
#if QT_CONFIG(shortcut)
        self.bSetup.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.lbIneach.setText(QCoreApplication.translate("InstallForm", u"Synchronize In", None))
#if QT_CONFIG(whatsthis)
        self.txtSyncIns.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtSyncIns.setInputMask(QCoreApplication.translate("InstallForm", u"000000", None))
        self.txtSyncIns.setText("")
        self.txtSyncIns.setPlaceholderText(QCoreApplication.translate("InstallForm", u"120.0", None))
        self.bPing.setText(QCoreApplication.translate("InstallForm", u"&Ping", None))
#if QT_CONFIG(shortcut)
        self.bPing.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(whatsthis)
        self.txtWebport.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtWebport.setText("")
        self.txtWebport.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8900", None))
        self.lbPort_2.setText(QCoreApplication.translate("InstallForm", u"/", None))
        self.chkReverseProxy.setText(QCoreApplication.translate("InstallForm", u"Via Proxy ", None))
        self.lbPublicIP.setText(QCoreApplication.translate("InstallForm", u"Public IP", None))
#if QT_CONFIG(whatsthis)
        self.txtPort_proxy.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPort_proxy.setText("")
        self.txtPort_proxy.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8964", None))
#if QT_CONFIG(whatsthis)
        self.txtWebport_proxy.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtWebport_proxy.setText("")
        self.txtWebport_proxy.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8900", None))
#if QT_CONFIG(whatsthis)
        self.txtIP_proxy.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtIP_proxy.setText("")
        self.txtIP_proxy.setPlaceholderText(QCoreApplication.translate("InstallForm", u"0.0.0.0", None))
        self.lbPort_3.setText(QCoreApplication.translate("InstallForm", u"/", None))
        self.lbPort_4.setText(QCoreApplication.translate("InstallForm", u"Port", None))
#if QT_CONFIG(whatsthis)
        self.txtimeout.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtimeout.setInputMask(QCoreApplication.translate("InstallForm", u"0000", None))
        self.txtimeout.setText(QCoreApplication.translate("InstallForm", u"12", None))
        self.txtimeout.setPlaceholderText(QCoreApplication.translate("InstallForm", u"10", None))
        self.lbTimeout.setText(QCoreApplication.translate("InstallForm", u"Timeout(s)", None))
        self.lblink.setText(QCoreApplication.translate("InstallForm", u"Portfolio is based on Open Source Projects.", None))
        self.menuPortfolio_0_7.setTitle(QCoreApplication.translate("InstallForm", u"Portfolio Synode 0.7", None))
    # retranslateUi

