# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTextEdit, QWidget)

class Ui_InstallForm(object):
    def setupUi(self, InstallForm):
        if not InstallForm.objectName():
            InstallForm.setObjectName(u"InstallForm")
        InstallForm.setWindowModality(Qt.NonModal)
        InstallForm.setEnabled(True)
        InstallForm.resize(960, 447)
        InstallForm.setMinimumSize(QSize(960, 400))
        InstallForm.setMaximumSize(QSize(960, 1280))
        InstallForm.setWindowTitle(u"Portfolio Synode 0.7")
        icon = QIcon()
        icon.addFile(u"res/ic108x64.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u"res/ic108x64.png", QSize(), QIcon.Disabled, QIcon.Off)
        InstallForm.setWindowIcon(icon)
        self.actionAbout = QAction(InstallForm)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(InstallForm)
        self.centralwidget.setObjectName(u"centralwidget")
        self.jservLines = QTextEdit(self.centralwidget)
        self.jservLines.setObjectName(u"jservLines")
        self.jservLines.setGeometry(QRect(110, 135, 521, 71))
        self.jservLines.setMaximumSize(QSize(8000, 400))
        self.gboxRegistry = QGroupBox(self.centralwidget)
        self.gboxRegistry.setObjectName(u"gboxRegistry")
        self.gboxRegistry.setGeometry(QRect(10, 0, 941, 131))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxRegistry.sizePolicy().hasHeightForWidth())
        self.gboxRegistry.setSizePolicy(sizePolicy)
        self.lbCommunity = QLabel(self.gboxRegistry)
        self.lbCommunity.setObjectName(u"lbCommunity")
        self.lbCommunity.setGeometry(QRect(13, 100, 91, 20))
        self.txtDomain = QLineEdit(self.gboxRegistry)
        self.txtDomain.setObjectName(u"txtDomain")
        self.txtDomain.setEnabled(True)
        self.txtDomain.setGeometry(QRect(319, 96, 122, 27))
        self.txtDomain.setMaxLength(12)
        self.lbRetry = QLabel(self.gboxRegistry)
        self.lbRetry.setObjectName(u"lbRetry")
        self.lbRetry.setGeometry(QRect(520, 64, 61, 20))
        self.txtPswd2 = QLineEdit(self.gboxRegistry)
        self.txtPswd2.setObjectName(u"txtPswd2")
        self.txtPswd2.setEnabled(False)
        self.txtPswd2.setGeometry(QRect(580, 61, 171, 27))
        self.txtPswd2.setMaxLength(32)
        self.txtPswd2.setEchoMode(QLineEdit.Password)
        self.lbAdminId = QLabel(self.gboxRegistry)
        self.lbAdminId.setObjectName(u"lbAdminId")
        self.lbAdminId.setGeometry(QRect(20, 64, 71, 20))
        self.txtPswd = QLineEdit(self.gboxRegistry)
        self.txtPswd.setObjectName(u"txtPswd")
        self.txtPswd.setEnabled(False)
        self.txtPswd.setGeometry(QRect(320, 61, 141, 27))
        self.txtPswd.setMaxLength(32)
        self.txtPswd.setEchoMode(QLineEdit.Password)
        self.txtAdminId = QLineEdit(self.gboxRegistry)
        self.txtAdminId.setObjectName(u"txtAdminId")
        self.txtAdminId.setEnabled(False)
        self.txtAdminId.setGeometry(QRect(100, 61, 131, 27))
        self.txtAdminId.setMaxLength(12)
        self.lbPswd = QLabel(self.gboxRegistry)
        self.lbPswd.setObjectName(u"lbPswd")
        self.lbPswd.setGeometry(QRect(250, 64, 70, 19))
        self.lbRegfolder = QLabel(self.gboxRegistry)
        self.lbRegfolder.setObjectName(u"lbRegfolder")
        self.lbRegfolder.setGeometry(QRect(39, 32, 61, 20))
        self.txtResroot = QLineEdit(self.gboxRegistry)
        self.txtResroot.setObjectName(u"txtResroot")
        self.txtResroot.setEnabled(False)
        self.txtResroot.setGeometry(QRect(100, 29, 651, 27))
        self.bCreateDomain = QPushButton(self.gboxRegistry)
        self.bCreateDomain.setObjectName(u"bCreateDomain")
        self.bCreateDomain.setEnabled(False)
        self.bCreateDomain.setGeometry(QRect(760, 96, 171, 28))
        self.lbHelplink = QLabel(self.gboxRegistry)
        self.lbHelplink.setObjectName(u"lbHelplink")
        self.lbHelplink.setGeometry(QRect(890, 0, 71, 20))
        self.lbHelplink.setOpenExternalLinks(True)
        self.lbDomain = QLabel(self.gboxRegistry)
        self.lbDomain.setObjectName(u"lbDomain")
        self.lbDomain.setGeometry(QRect(260, 100, 61, 20))
        self.txtOrgid = QLineEdit(self.gboxRegistry)
        self.txtOrgid.setObjectName(u"txtOrgid")
        self.txtOrgid.setEnabled(True)
        self.txtOrgid.setGeometry(QRect(100, 96, 111, 27))
        self.txtOrgid.setMaxLength(12)
        self.bCommDropdown = QPushButton(self.gboxRegistry)
        self.bCommDropdown.setObjectName(u"bCommDropdown")
        self.bCommDropdown.setEnabled(False)
        self.bCommDropdown.setGeometry(QRect(210, 96, 22, 27))
        font = QFont()
        font.setPointSize(12)
        self.bCommDropdown.setFont(font)
        icon1 = QIcon()
        icon1.addFile(u"res/input_combobox.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.bCommDropdown.setIcon(icon1)
        self.bCommDropdown.setIconSize(QSize(24, 22))
        self.bLogin = QPushButton(self.gboxRegistry)
        self.bLogin.setObjectName(u"bLogin")
        self.bLogin.setEnabled(False)
        self.bLogin.setGeometry(QRect(760, 60, 171, 28))
        self.bSignup = QPushButton(self.gboxRegistry)
        self.bSignup.setObjectName(u"bSignup")
        self.bSignup.setEnabled(False)
        self.bSignup.setGeometry(QRect(760, 28, 171, 28))
        self.txtDompswd = QLineEdit(self.gboxRegistry)
        self.txtDompswd.setObjectName(u"txtDompswd")
        self.txtDompswd.setEnabled(True)
        self.txtDompswd.setGeometry(QRect(580, 96, 171, 27))
        self.txtDompswd.setMaxLength(12)
        self.lbDomain_2 = QLabel(self.gboxRegistry)
        self.lbDomain_2.setObjectName(u"lbDomain_2")
        self.lbDomain_2.setGeometry(QRect(477, 100, 101, 20))
        self.bDomainDropdown = QPushButton(self.gboxRegistry)
        self.bDomainDropdown.setObjectName(u"bDomainDropdown")
        self.bDomainDropdown.setEnabled(False)
        self.bDomainDropdown.setGeometry(QRect(440, 96, 22, 27))
        self.bDomainDropdown.setFont(font)
        self.bDomainDropdown.setIcon(icon1)
        self.bDomainDropdown.setIconSize(QSize(24, 22))
        self.lbQr = QLabel(self.centralwidget)
        self.lbQr.setObjectName(u"lbQr")
        self.lbQr.setGeometry(QRect(784, 141, 161, 171))
        self.lbQr.setMaximumSize(QSize(200, 200))
        self.lbQr.setAutoFillBackground(False)
        self.bValidate = QPushButton(self.centralwidget)
        self.bValidate.setObjectName(u"bValidate")
        self.bValidate.setGeometry(QRect(540, 362, 91, 30))
        self.bWinserv = QPushButton(self.centralwidget)
        self.bWinserv.setObjectName(u"bWinserv")
        self.bWinserv.setEnabled(False)
        self.bWinserv.setGeometry(QRect(640, 362, 311, 30))
        self.bSetup = QPushButton(self.centralwidget)
        self.bSetup.setObjectName(u"bSetup")
        self.bSetup.setEnabled(True)
        self.bSetup.setGeometry(QRect(780, 323, 171, 28))
        self.bPing = QPushButton(self.centralwidget)
        self.bPing.setObjectName(u"bPing")
        self.bPing.setEnabled(True)
        self.bPing.setGeometry(QRect(641, 180, 121, 25))
        self.txtimeout = QLineEdit(self.centralwidget)
        self.txtimeout.setObjectName(u"txtimeout")
        self.txtimeout.setGeometry(QRect(720, 137, 41, 20))
        font1 = QFont()
        font1.setFamilies([u"Serif"])
        font1.setPointSize(10)
        self.txtimeout.setFont(font1)
        self.txtimeout.setMaxLength(4)
        self.txtimeout.setReadOnly(False)
        self.lbTimeout = QLabel(self.centralwidget)
        self.lbTimeout.setObjectName(u"lbTimeout")
        self.lbTimeout.setGeometry(QRect(640, 138, 81, 16))
        self.lblink = QLabel(self.centralwidget)
        self.lblink.setObjectName(u"lblink")
        self.lblink.setGeometry(QRect(30, 380, 381, 20))
        self.lblink.setOpenExternalLinks(True)
        self.lbVolume_2 = QLabel(self.centralwidget)
        self.lbVolume_2.setObjectName(u"lbVolume_2")
        self.lbVolume_2.setGeometry(QRect(10, 140, 91, 20))
        self.gboxLocal = QGroupBox(self.centralwidget)
        self.gboxLocal.setObjectName(u"gboxLocal")
        self.gboxLocal.setGeometry(QRect(10, 200, 761, 153))
        self.lbPort_4 = QLabel(self.gboxLocal)
        self.lbPort_4.setObjectName(u"lbPort_4")
        self.lbPort_4.setGeometry(QRect(480, 90, 41, 20))
        self.lbJservs = QLabel(self.gboxLocal)
        self.lbJservs.setObjectName(u"lbJservs")
        self.lbJservs.setGeometry(QRect(411, 30, 311, 21))
        self.lbJservs.setCursor(QCursor(Qt.IBeamCursor))
        self.txtPort_proxy = QLineEdit(self.gboxLocal)
        self.txtPort_proxy.setObjectName(u"txtPort_proxy")
        self.txtPort_proxy.setGeometry(QRect(631, 86, 121, 27))
        self.txtPort_proxy.setMaxLength(6)
        self.txtSynode = QLineEdit(self.gboxLocal)
        self.txtSynode.setObjectName(u"txtSynode")
        self.txtSynode.setGeometry(QRect(100, 56, 131, 27))
        self.txtSynode.setMaxLength(12)
        self.lbVolume = QLabel(self.gboxLocal)
        self.lbVolume.setObjectName(u"lbVolume")
        self.lbVolume.setGeometry(QRect(41, 122, 51, 19))
        self.lbSynode = QLabel(self.gboxLocal)
        self.lbSynode.setObjectName(u"lbSynode")
        self.lbSynode.setGeometry(QRect(43, 59, 51, 20))
        self.lbIP = QLabel(self.gboxLocal)
        self.lbIP.setObjectName(u"lbIP")
        self.lbIP.setGeometry(QRect(261, 59, 69, 19))
        self.chkReverseProxy = QCheckBox(self.gboxLocal)
        self.chkReverseProxy.setObjectName(u"chkReverseProxy")
        self.chkReverseProxy.setGeometry(QRect(100, 90, 62, 21))
        self.lbPort = QLabel(self.gboxLocal)
        self.lbPort.setObjectName(u"lbPort")
        self.lbPort.setGeometry(QRect(480, 59, 41, 20))
        self.txtWebport = QLineEdit(self.gboxLocal)
        self.txtWebport.setObjectName(u"txtWebport")
        self.txtWebport.setGeometry(QRect(520, 56, 101, 27))
        self.txtWebport.setMaxLength(6)
        self.bVolpath = QPushButton(self.gboxLocal)
        self.bVolpath.setObjectName(u"bVolpath")
        self.bVolpath.setGeometry(QRect(630, 122, 121, 28))
        self.bVolpath.setFont(font)
        icon2 = QIcon()
        icon2.addFile(u"res/volume.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.bVolpath.setIcon(icon2)
        self.bVolpath.setIconSize(QSize(24, 24))
        self.txtIP = QLineEdit(self.gboxLocal)
        self.txtIP.setObjectName(u"txtIP")
        self.txtIP.setGeometry(QRect(321, 56, 141, 27))
        self.txtIP.setMaxLength(39)
        self.txtWebport_proxy = QLineEdit(self.gboxLocal)
        self.txtWebport_proxy.setObjectName(u"txtWebport_proxy")
        self.txtWebport_proxy.setGeometry(QRect(520, 86, 101, 27))
        self.txtWebport_proxy.setMaxLength(6)
        self.lbPublicIP = QLabel(self.gboxLocal)
        self.lbPublicIP.setObjectName(u"lbPublicIP")
        self.lbPublicIP.setGeometry(QRect(255, 90, 61, 20))
        self.txtIP_proxy = QLineEdit(self.gboxLocal)
        self.txtIP_proxy.setObjectName(u"txtIP_proxy")
        self.txtIP_proxy.setGeometry(QRect(321, 86, 141, 27))
        self.txtIP_proxy.setMaxLength(39)
        self.txtPort = QLineEdit(self.gboxLocal)
        self.txtPort.setObjectName(u"txtPort")
        self.txtPort.setGeometry(QRect(631, 56, 121, 27))
        self.txtPort.setMaxLength(6)
        self.txtSyncIns = QLineEdit(self.gboxLocal)
        self.txtSyncIns.setObjectName(u"txtSyncIns")
        self.txtSyncIns.setEnabled(False)
        self.txtSyncIns.setGeometry(QRect(320, 30, 81, 21))
        self.txtSyncIns.setMaxLength(4)
        self.txtVolpath = QLineEdit(self.gboxLocal)
        self.txtVolpath.setObjectName(u"txtVolpath")
        self.txtVolpath.setGeometry(QRect(101, 122, 521, 27))
        self.chkHub = QCheckBox(self.gboxLocal)
        self.chkHub.setObjectName(u"chkHub")
        self.chkHub.setGeometry(QRect(100, 30, 51, 21))
        self.lbJservs_2 = QLabel(self.gboxLocal)
        self.lbJservs_2.setObjectName(u"lbJservs_2")
        self.lbJservs_2.setGeometry(QRect(260, 30, 61, 21))
        self.lbJservs_2.setCursor(QCursor(Qt.IBeamCursor))
        InstallForm.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(InstallForm)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 960, 24))
        InstallForm.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(InstallForm)
        self.statusbar.setObjectName(u"statusbar")
        InstallForm.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtResroot, self.txtAdminId)
        QWidget.setTabOrder(self.txtAdminId, self.txtPswd)
        QWidget.setTabOrder(self.txtPswd, self.txtPswd2)
        QWidget.setTabOrder(self.txtPswd2, self.bSignup)
        QWidget.setTabOrder(self.bSignup, self.bLogin)
        QWidget.setTabOrder(self.bLogin, self.txtOrgid)
        QWidget.setTabOrder(self.txtOrgid, self.bCommDropdown)
        QWidget.setTabOrder(self.bCommDropdown, self.txtDomain)
        QWidget.setTabOrder(self.txtDomain, self.bDomainDropdown)
        QWidget.setTabOrder(self.bDomainDropdown, self.txtDompswd)
        QWidget.setTabOrder(self.txtDompswd, self.bCreateDomain)
        QWidget.setTabOrder(self.bCreateDomain, self.jservLines)
        QWidget.setTabOrder(self.jservLines, self.txtimeout)
        QWidget.setTabOrder(self.txtimeout, self.bPing)
        QWidget.setTabOrder(self.bPing, self.chkHub)
        QWidget.setTabOrder(self.chkHub, self.txtSyncIns)
        QWidget.setTabOrder(self.txtSyncIns, self.txtSynode)
        QWidget.setTabOrder(self.txtSynode, self.txtIP)
        QWidget.setTabOrder(self.txtIP, self.txtWebport)
        QWidget.setTabOrder(self.txtWebport, self.txtPort)
        QWidget.setTabOrder(self.txtPort, self.chkReverseProxy)
        QWidget.setTabOrder(self.chkReverseProxy, self.txtIP_proxy)
        QWidget.setTabOrder(self.txtIP_proxy, self.txtWebport_proxy)
        QWidget.setTabOrder(self.txtWebport_proxy, self.txtPort_proxy)
        QWidget.setTabOrder(self.txtPort_proxy, self.txtVolpath)
        QWidget.setTabOrder(self.txtVolpath, self.bVolpath)
        QWidget.setTabOrder(self.bVolpath, self.bSetup)
        QWidget.setTabOrder(self.bSetup, self.bValidate)
        QWidget.setTabOrder(self.bValidate, self.bWinserv)

        self.retranslateUi(InstallForm)

        QMetaObject.connectSlotsByName(InstallForm)
    # setupUi

    def retranslateUi(self, InstallForm):
        self.actionAbout.setText(QCoreApplication.translate("InstallForm", u"About", None))
#if QT_CONFIG(whatsthis)
        self.jservLines.setWhatsThis(QCoreApplication.translate("InstallForm", u"<a href='#'>Configure Synodes' service port.</a>", None))
#endif // QT_CONFIG(whatsthis)
        self.gboxRegistry.setTitle(QCoreApplication.translate("InstallForm", u"Synchronization Domain Identity - Market TEST", None))
        self.lbCommunity.setText(QCoreApplication.translate("InstallForm", u"Community:", None))
#if QT_CONFIG(whatsthis)
        self.txtDomain.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtDomain.setText(QCoreApplication.translate("InstallForm", u"zsu", None))
        self.txtDomain.setPlaceholderText(QCoreApplication.translate("InstallForm", u"12 Bit Market wide ID, must not null", None))
        self.lbRetry.setText(QCoreApplication.translate("InstallForm", u"Confirm:", None))
#if QT_CONFIG(whatsthis)
        self.txtPswd2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPswd2.setText("")
        self.txtPswd2.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Confirm Password", None))
        self.lbAdminId.setText(QCoreApplication.translate("InstallForm", u"<html><head/><body><p align=\"right\">Admin:</p></body></html>", None))
#if QT_CONFIG(whatsthis)
        self.txtPswd.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPswd.setText("")
        self.txtPswd.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Max 32 Chars", None))
#if QT_CONFIG(whatsthis)
        self.txtAdminId.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtAdminId.setText("")
        self.txtAdminId.setPlaceholderText(QCoreApplication.translate("InstallForm", u"admin ID", None))
        self.lbPswd.setText(QCoreApplication.translate("InstallForm", u"Password:", None))
        self.lbRegfolder.setText(QCoreApplication.translate("InstallForm", u"Registry:", None))
#if QT_CONFIG(whatsthis)
        self.txtResroot.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtResroot.setText(QCoreApplication.translate("InstallForm", u"http://central.demo.test", None))
        self.txtResroot.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Path to the registered resources.", None))
        self.bCreateDomain.setText(QCoreApplication.translate("InstallForm", u"&Register Domain", None))
#if QT_CONFIG(shortcut)
        self.bCreateDomain.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.lbHelplink.setText(QCoreApplication.translate("InstallForm", u"Help", None))
        self.lbDomain.setText(QCoreApplication.translate("InstallForm", u"Domain:", None))
#if QT_CONFIG(whatsthis)
        self.txtOrgid.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtOrgid.setText(QCoreApplication.translate("InstallForm", u"ura", None))
        self.txtOrgid.setPlaceholderText(QCoreApplication.translate("InstallForm", u"12 Bit Market wide ID, must not null", None))
        self.bCommDropdown.setText("")
#if QT_CONFIG(shortcut)
        self.bCommDropdown.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.bLogin.setText(QCoreApplication.translate("InstallForm", u"&Login", None))
#if QT_CONFIG(shortcut)
        self.bLogin.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.bSignup.setText(QCoreApplication.translate("InstallForm", u"Sign &up", None))
#if QT_CONFIG(shortcut)
        self.bSignup.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(whatsthis)
        self.txtDompswd.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtDompswd.setText("")
        self.txtDompswd.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Used in Domain", None))
        self.lbDomain_2.setText(QCoreApplication.translate("InstallForm", u"Domain Token:", None))
        self.bDomainDropdown.setText("")
#if QT_CONFIG(shortcut)
        self.bDomainDropdown.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.lbQr.setText("")
        self.bValidate.setText(QCoreApplication.translate("InstallForm", u"&Test Run", None))
#if QT_CONFIG(shortcut)
        self.bValidate.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.bWinserv.setText(QCoreApplication.translate("InstallForm", u"Install as &Windows Service", None))
#if QT_CONFIG(shortcut)
        self.bWinserv.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.bSetup.setText(QCoreApplication.translate("InstallForm", u"&Save", None))
#if QT_CONFIG(shortcut)
        self.bSetup.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.bPing.setText(QCoreApplication.translate("InstallForm", u"&Ping", None))
#if QT_CONFIG(shortcut)
        self.bPing.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(whatsthis)
        self.txtimeout.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtimeout.setInputMask(QCoreApplication.translate("InstallForm", u"0000", None))
        self.txtimeout.setText(QCoreApplication.translate("InstallForm", u"12", None))
        self.txtimeout.setPlaceholderText(QCoreApplication.translate("InstallForm", u"10", None))
        self.lbTimeout.setText(QCoreApplication.translate("InstallForm", u"Timeout(s)", None))
        self.lblink.setText(QCoreApplication.translate("InstallForm", u"Portfolio is based on Open Source Projects.", None))
        self.lbVolume_2.setText(QCoreApplication.translate("InstallForm", u"Peer Services", None))
        self.gboxLocal.setTitle(QCoreApplication.translate("InstallForm", u"Local Settings", None))
        self.lbPort_4.setText(QCoreApplication.translate("InstallForm", u"Port", None))
        self.lbJservs.setText(QCoreApplication.translate("InstallForm", u"seconds synchronize  with the other peers.", None))
#if QT_CONFIG(whatsthis)
        self.txtPort_proxy.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPort_proxy.setText("")
        self.txtPort_proxy.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8964", None))
#if QT_CONFIG(whatsthis)
        self.txtSynode.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtSynode.setText("")
        self.txtSynode.setPlaceholderText(QCoreApplication.translate("InstallForm", u"12 Bit GUID, must not null", None))
        self.lbVolume.setText(QCoreApplication.translate("InstallForm", u"Volume", None))
        self.lbSynode.setText(QCoreApplication.translate("InstallForm", u"Synode", None))
        self.lbIP.setText(QCoreApplication.translate("InstallForm", u"Local IP", None))
        self.chkReverseProxy.setText(QCoreApplication.translate("InstallForm", u"Proxy ", None))
        self.lbPort.setText(QCoreApplication.translate("InstallForm", u"Port", None))
#if QT_CONFIG(whatsthis)
        self.txtWebport.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtWebport.setText("")
        self.txtWebport.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8900", None))
        self.bVolpath.setText(QCoreApplication.translate("InstallForm", u"&Volume", None))
#if QT_CONFIG(shortcut)
        self.bVolpath.setShortcut(QCoreApplication.translate("InstallForm", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(whatsthis)
        self.txtIP.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtIP.setText("")
        self.txtIP.setPlaceholderText(QCoreApplication.translate("InstallForm", u"0.0.0.0", None))
#if QT_CONFIG(whatsthis)
        self.txtWebport_proxy.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtWebport_proxy.setText("")
        self.txtWebport_proxy.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8900", None))
        self.lbPublicIP.setText(QCoreApplication.translate("InstallForm", u"Public IP", None))
#if QT_CONFIG(whatsthis)
        self.txtIP_proxy.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtIP_proxy.setText("")
        self.txtIP_proxy.setPlaceholderText(QCoreApplication.translate("InstallForm", u"0.0.0.0", None))
#if QT_CONFIG(whatsthis)
        self.txtPort.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtPort.setText("")
        self.txtPort.setPlaceholderText(QCoreApplication.translate("InstallForm", u"E. g. 8964", None))
#if QT_CONFIG(whatsthis)
        self.txtSyncIns.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtSyncIns.setInputMask(QCoreApplication.translate("InstallForm", u"0000", None))
        self.txtSyncIns.setText("")
        self.txtSyncIns.setPlaceholderText(QCoreApplication.translate("InstallForm", u"120.0", None))
#if QT_CONFIG(whatsthis)
        self.txtVolpath.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.txtVolpath.setText(QCoreApplication.translate("InstallForm", u"../vol", None))
        self.txtVolpath.setPlaceholderText(QCoreApplication.translate("InstallForm", u"Volume is where the data saved at local node.", None))
        self.chkHub.setText(QCoreApplication.translate("InstallForm", u"hub", None))
        self.lbJservs_2.setText(QCoreApplication.translate("InstallForm", u"In every", None))
        pass
    # retranslateUi

