# docker-compose -f docker-compose-mysql.yml up -d
version: '3'

services:

  mysqldb:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: odys-z.github.io
      MYSQL_DATABASE: album-cloud
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE # https://stackoverflow.com/a/55706057/7362888
    volumes:
      - "./volume/my.conf:/etc/mysql/conf.d/config-file.cnf"

      # Docker on windows is runing in VirtualBox: https://stackoverflow.com/a/36721432/7362888
      # Only know copy data with Windows Docker Desktop ...
      # Needing tested on linux
      - "album.mysql:/var/lib/mysql:rw"

volumes:
    album.mysql:
        external: false # https://stackoverflow.com/a/37707335/7362888
