FROM openjdk:17

COPY target/docsync.jserv-0.2.0-SNAPSHOT.jar /synodetier/

WORKDIR /synodetier

CMD ["java", "-jar", "docsync.jserv-0.2.0-SNAPSHOT.jar"]

# mkdir products
# cp ../../../../ever/products/album-web/index.html products

# then, mount with volume

